export const STORAGE_REQUEST = "STORAGE_REQUEST";
export const STORAGE_SUCCESS = "STORAGE_SUCCESS";
export const STORAGE_ERROR = "STORAGE_ERROR";


export const IMAGE_SAVE_REQUEST = "IMAGE_SAVE_REQUEST";
export const IMAGE_SAVE_SUCCESS = "IMAGE_SAVE_SUCCESS"
export const IMAGE_SAVE_ERROR = "IMAGE_SAVE_ERROR"